packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.9.0
  prettier: ^3.3.2
  typescript: ^5.5.4
  zod: ^3.23.8
  tailwindcss: ^3.4.10
  next: "14.2.5"
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  "@types/node": ^20.14.15

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
